// Auto-generated catalog from catalogo_mikado.xlsx
const CATALOG_TIMESTAMP = 1785292472;
const PRODUCTS_DATA = [
  {
    "id": 1,
    "codigo": "MKD-001",
    "brand": "BEAUTY OF JOSEON",
    "title": "Relief Sun: Rice + Probiotics SPF50+ PA++++ - 50ml",
    "category": "solares",
    "price": 84.0,
    "oldPrice": 94.0,
    "stock": 2,
    "discount": 0.1063829787234043,
    "rating": 5.0,
    "reviews": 5.0,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-001.jpg",
    "desc": "Protector solar orgánico ligero con 30% extracto de arroz. No deja capa blanca."
  },
  {
    "id": 2,
    "codigo": "MKD-002",
    "brand": "COSRX",
    "title": "Advanced Snail 96 Mucin Power Essence - 100ml",
    "category": "serums",
    "price": 88.0,
    "oldPrice": 110.0,
    "stock": 2,
    "discount": 0.19999999999999996,
    "rating": 4.6,
    "reviews": 4.6,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-002.jpg",
    "desc": "Esencia con 96% mucina de caracol. Repara la barrera cutánea y aporta brillo Glass Skin."
  },
  {
    "id": 3,
    "codigo": "MKD-003",
    "brand": "ANUA",
    "title": "Heartleaf 77% Soothing Toner - 250ml",
    "category": "tonicos",
    "price": 89.0,
    "oldPrice": 99.0,
    "stock": 0,
    "discount": 0.101010101010101,
    "rating": 4.8,
    "reviews": 4.8,
    "badge": "Agotado",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-003.webp",
    "desc": "Tónico calmante para pieles sensibles y propensas a rojeces o acné."
  },
  {
    "id": 4,
    "codigo": "MKD-004",
    "brand": "SKIN 1004",
    "title": "Madagascar Centella Ampoule - 100ml",
    "category": "serums",
    "price": 92.0,
    "oldPrice": 102.0,
    "stock": 0,
    "discount": 0.0980392156862745,
    "rating": 4.5,
    "reviews": 4.5,
    "badge": "Agotado",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-004.jpg",
    "desc": "Serum concentrado 100% Centella Asiática. Calma e hidrata intensamente."
  },
  {
    "id": 5,
    "codigo": "MKD-005",
    "brand": "LANEIGE",
    "title": "Lip Sleeping Mask EX [Berry] - 20g",
    "category": "mascarillas",
    "price": 75.0,
    "oldPrice": null,
    "stock": 0,
    "discount": 0.0,
    "rating": 4.8,
    "reviews": 4.8,
    "badge": "Agotado",
    "badgeClass": "",
    "img": "imagenes_productos/MKD-005.webp",
    "desc": "Mascarilla nocturna de labios de frutos rojos. Hidratación profunda 24h."
  },
  {
    "id": 6,
    "codigo": "MKD-006",
    "brand": "SKIN 1004",
    "title": "Pure Cleansing Oil - 200ml",
    "category": "limpiadores",
    "price": 99.0,
    "oldPrice": null,
    "stock": 2,
    "discount": 0.0,
    "rating": 4.6,
    "reviews": 4.6,
    "badge": "En Stock",
    "badgeClass": "accent",
    "img": "imagenes_productos/MKD-006.webp",
    "desc": "Aceite limpiador hidrofílico con 14 aceites vegetales. Remueve todo el maquillaje."
  },
  {
    "id": 7,
    "codigo": "MKD-007",
    "brand": "APLB",
    "title": "Tranexamic Acid Niacinamide Body Lotion - 300ml",
    "category": "hidratantes",
    "price": 100.0,
    "oldPrice": 120.0,
    "stock": 1,
    "discount": 0.16666666666666663,
    "rating": 4.7,
    "reviews": 4.7,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-007.jpg",
    "desc": "Es una crema corporal hidratante y despigmentante, formulada con ácido tranexámico y niacinamida, diseñada para unificar el tono de la piel, aclarar manchas oscuras y calmar la sequedad sin dejar sensación pegajosa."
  },
  {
    "id": 8,
    "codigo": "MKD-008",
    "brand": "APLB",
    "title": "Loción Corporal Glutathione Niacinamide - 300ml",
    "category": "hidratantes",
    "price": 100.0,
    "oldPrice": 110.0,
    "stock": 1,
    "discount": 0.09090909090909094,
    "rating": 4.8,
    "reviews": 4.8,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-008.jpg",
    "desc": "La Loción Corporal Glutathione Niacinamide de APLB aporta un efecto iluminador y suavizante a tu rutina diaria de cuidado corporal."
  },
  {
    "id": 9,
    "codigo": "MKD-009",
    "brand": "ARENCIA",
    "title": "Holy Hyssop Serum 30 - 50g",
    "category": "serums",
    "price": 99.0,
    "oldPrice": 125.0,
    "stock": 3,
    "discount": 0.20799999999999996,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-009.jpg",
    "desc": "Sérum facial concentrado formulado con extracto de hisopo sagrado. Calma las pieles irritadas, restaura la barrera cutánea y proporciona un impulso intensivo de hidratación y vitalidad. Perfecto para devolverle el confort, equilibrio y frescura a rostros cansados o sensibles."
  },
  {
    "id": 10,
    "codigo": "MKD-010",
    "brand": "BEAUTY OF JOSEON",
    "title": "Sérum Contorno de Ojos Revive Eye Serum - 30ml",
    "category": "contorno de ojos",
    "price": 84.0,
    "oldPrice": 90.0,
    "stock": 2,
    "discount": 0.06666666666666665,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-010.jpg",
    "desc": "Tratamiento intensivo para la mirada enriquecido con retinal y extracto de ginseng. Su fórmula suave pero eficaz ayuda a atenuar líneas de expresión, combatir ojeras y firmeza en la delicada zona de los ojos, dejando la mirada descansada, juvenil y rejuvenecida."
  },
  {
    "id": 11,
    "codigo": "MKD-011",
    "brand": "BEAUTY OF JOSEON",
    "title": "Revive Serum: Ginseng + Snail Mucin - 10ml",
    "category": "serums",
    "price": 20.0,
    "oldPrice": 25.0,
    "stock": 2,
    "discount": 0.19999999999999996,
    "rating": 4.7,
    "reviews": 4.7,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-011.jpg",
    "desc": "Un potente sérum regenerador que une el poder antioxidante del ginseng con la nutrición de la mucina de caracol. Repara la piel dañada, combate los signos del envejecimiento y mejora la elasticidad para revelar un rostro firme, hidratado y lleno de vitalidad natural."
  },
  {
    "id": 12,
    "codigo": "MKD-012",
    "brand": "CELIMAX",
    "title": "Protector Solar Oil Control Light Sunscreen - 40ml",
    "category": "solares",
    "price": 92.0,
    "oldPrice": 100.0,
    "stock": 2,
    "discount": 0.07999999999999996,
    "rating": 4.7,
    "reviews": 4.7,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-012.jpg",
    "desc": "Protector solar ligero diseñado especialmente para pieles mixtas a grasas. Ofrece alta protección UV mientras controla el exceso de sebo y los brillos durante todo el día. De acabado fresco y mate, no deja rastro blanco ni obstruye los poros."
  },
  {
    "id": 13,
    "codigo": "MKD-013",
    "brand": "CELIMAX",
    "title": "Set de Prueba The Real Noni Starter Kit",
    "category": "kit",
    "price": 110.0,
    "oldPrice": null,
    "stock": 6,
    "discount": 0.0,
    "rating": 4.8,
    "reviews": 4.8,
    "badge": "En Stock",
    "badgeClass": "accent",
    "img": "imagenes_productos/MKD-013.jpg",
    "desc": "El kit de iniciación perfecto para descubrir las bondades del fruto de Noni. Contiene una rutina completa en formato viaje diseñada para calmar, nutrir y revitalizar la piel estresada o sensible. Ideal para llevar a todos lados o probar antes del tamaño regular."
  },
  {
    "id": 14,
    "codigo": "MKD-014",
    "brand": "CELIMAX",
    "title": "Limpiador en Burbujas para Acné The Real Noni - 155ml",
    "category": "limpiadores",
    "price": 99.0,
    "oldPrice": 110.0,
    "stock": 1,
    "discount": 0.09999999999999998,
    "rating": 4.5,
    "reviews": 4.5,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-014.jpg",
    "desc": "Limpiador facial en espuma microburbujeante enriquecido con extracto de Noni y activos antiacné. Limpia suavemente en profundidad, purifica los poros sin resecar y ayuda a calmar brotes y rojeces. Deja la piel limpia, suave y totalmente equilibrada."
  },
  {
    "id": 15,
    "codigo": "MKD-015",
    "brand": "CELIMAX",
    "title": "Aceite Limpiador Derma Nature Fresh Blackhead Jojoba Cleansing Oil - 150ml",
    "category": "limpiadores",
    "price": 99.0,
    "oldPrice": 105.0,
    "stock": 2,
    "discount": 0.05714285714285716,
    "rating": 4.7,
    "reviews": 4.7,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-015.jpg",
    "desc": "Aceite limpiador con aceite de jojoba que disuelve eficazmente el maquillaje, la grasa acumulada y los puntos negros sin irritar. Se emulsiona fácilmente con agua, dejando la piel limpia, fresca, profundamente purificada y libre de impurezas."
  },
  {
    "id": 16,
    "codigo": "MKD-016",
    "brand": "CELIMAX",
    "title": "Sérum Iluminador Pore + Dark Spot Brightening - 30ml",
    "category": "serums",
    "price": 95.0,
    "oldPrice": 105.0,
    "stock": 1,
    "discount": 0.09523809523809523,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-016.jpg",
    "desc": "Tratamiento especializado para difuminar manchas hiperpigmentadas y minimizar la apariencia de los poros dilatados. Formulado para unificar el tono de la piel, devolver el brillo natural y mejorar la textura cutánea, dejando el rostro uniforme y radiante."
  },
  {
    "id": 17,
    "codigo": "MKD-017",
    "brand": "CELIMAX",
    "title": "Protector Solar en Barra Oil Control Mattifying - 19g",
    "category": "solares",
    "price": 92.0,
    "oldPrice": null,
    "stock": 2,
    "discount": 0.0,
    "rating": 4.6,
    "reviews": 4.6,
    "badge": "En Stock",
    "badgeClass": "accent",
    "img": "imagenes_productos/MKD-017.jpg",
    "desc": "Fotoprotección práctica y sin retoques complicados. Este protector solar en formato barra ofrece alta protección UV con efecto matificante. Controla la grasa, se desliza suavemente sobre la piel (incluso sobre el maquillaje) y es ideal para llevar en el bolso."
  },
  {
    "id": 18,
    "codigo": "MKD-018",
    "brand": "CELIMAX",
    "title": "Sérum Facial The Vita-A Retinal Shot Tightening Booster - 15ml",
    "category": "contorno de ojos",
    "price": 99.0,
    "oldPrice": 125.0,
    "stock": 6,
    "discount": 0.20799999999999996,
    "rating": 4.5,
    "reviews": 4.5,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-018.jpg",
    "desc": "Booster antiedad avanzado enriquecido con retinal. Ayuda a estimular la renovación celular, afinar la textura de la piel y mejorar visiblemente la firmeza y elasticidad. Un potente aliado para atenuar arrugas y revitalizar la tez con resultados profesionales."
  },
  {
    "id": 19,
    "codigo": "MKD-019",
    "brand": "CELIMAX",
    "title": "Ampolla Facial Noni Ampoule Calming + Radiance - 100ml",
    "category": "serums",
    "price": 120.0,
    "oldPrice": 140.0,
    "stock": 3,
    "discount": 0.1428571428571429,
    "rating": 4.8,
    "reviews": 4.8,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-019.webp",
    "desc": "Ampolla nutritiva concentrada con extracto de superalimento Noni en presentación compacta. Aporta un alivio inmediato a la piel sensible, fortalece la barrera cutánea y proporciona una luminosidad saludable."
  },
  {
    "id": 20,
    "codigo": "MKD-020",
    "brand": "CELIMAX",
    "title": "Ampolla Facial Noni Ampoule Calming + Radiance - 30ml",
    "category": "serums",
    "price": 92.0,
    "oldPrice": 110.0,
    "stock": 1,
    "discount": 0.1636363636363637,
    "rating": 4.7,
    "reviews": 4.7,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-020.webp",
    "desc": "Ampolla nutritiva concentrada con extracto de superalimento Noni en presentación compacta. Aporta un alivio inmediato a la piel sensible, fortalece la barrera cutánea y proporciona una luminosidad saludable."
  },
  {
    "id": 21,
    "codigo": "MKD-021",
    "brand": "CELIMAX",
    "title": "Ampolla Facial Noni Ampoule Calming + Radiance - 50ml",
    "category": "serums",
    "price": 105.0,
    "oldPrice": 130.0,
    "stock": 1,
    "discount": 0.1923076923076923,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-021.jpg",
    "desc": "Ampolla nutritiva concentrada con extracto de superalimento Noni en presentación compacta. Aporta un alivio inmediato a la piel sensible, fortalece la barrera cutánea y proporciona una luminosidad saludable."
  },
  {
    "id": 22,
    "codigo": "MKD-022",
    "brand": "DR ALTHEA",
    "title": "Crema 345 Relief - 50ml",
    "category": "hidratantes",
    "price": 100.0,
    "oldPrice": null,
    "stock": 4,
    "discount": 0.0,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "accent",
    "img": "imagenes_productos/MKD-022.jpg",
    "desc": "Crema hidratante y calmante de textura ligera tipo gel. Formulada para restaurar la piel dañada, suavizar rojeces e irritaciones y reparar la barrera cutánea. Aporta confort duradero y una hidratación profunda sin dejar sensación grasosa."
  },
  {
    "id": 23,
    "codigo": "MKD-023",
    "brand": "I'M FROM",
    "title": "Tónico de Arroz - 150ml",
    "category": "tonicos",
    "price": 109.0,
    "oldPrice": 119.0,
    "stock": 1,
    "discount": 0.08403361344537819,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-023.webp",
    "desc": "Tónico iluminador formulado con un 77.78% de extracto de arroz puro. Hidrata profundamente, suaviza las zonas ásperas y aporta un efecto glass skin radiante. Su textura bifásica equilibra la hidratación y nutrición de la piel cansada u opaca."
  },
  {
    "id": 24,
    "codigo": "MKD-024",
    "brand": "MARY & MAY",
    "title": "Mask Collagen - 400g",
    "category": "mascarillas",
    "price": 128.0,
    "oldPrice": null,
    "stock": 1,
    "discount": 0.0,
    "rating": 4.7,
    "reviews": 4.7,
    "badge": "En Stock",
    "badgeClass": "accent",
    "img": "imagenes_productos/MKD-024.jpg",
    "desc": "Mascarillas faciales impregnadas en colágeno marino de bajo peso molecular. Diseñadas para devolver la elasticidad, firmeza y humectación al rostro. Un tratamiento intensivo diario para lucir una piel tersa, lisa, rejuvenecida y llena de vida."
  },
  {
    "id": 25,
    "codigo": "MKD-025",
    "brand": "MEDICUBE",
    "title": "Mascarilla de Salmón - 28g",
    "category": "mascarillas",
    "price": 22.0,
    "oldPrice": 26.0,
    "stock": 2,
    "discount": 0.15384615384615385,
    "rating": 4.6,
    "reviews": 4.6,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-025.jpg",
    "desc": "Mascarilla nutritiva enriquecida con ADN de salmón (PDRN). Ayuda a revitalizar la piel, potenciar la elasticidad y regenerar los tejidos apagados o dañados. Proporciona una recarga de hidratación y un acabado suave, terso y luminoso."
  },
  {
    "id": 26,
    "codigo": "MKD-026",
    "brand": "MEDICUBE",
    "title": "Mascarilla Gel - 75ml",
    "category": "mascarillas",
    "price": 109.0,
    "oldPrice": null,
    "stock": 1,
    "discount": 0.0,
    "rating": 4.5,
    "reviews": 4.5,
    "badge": "En Stock",
    "badgeClass": "accent",
    "img": "imagenes_productos/MKD-026.jpg",
    "desc": "Mascarilla de gel refrescante que se adhiere perfectamente al contorno facial para una máxima absorción de activos. Calma al instante la piel estresada, cierra visiblemente los poros e hidrata en profundidad, dejando un efecto de spa en casa."
  },
  {
    "id": 27,
    "codigo": "MKD-027",
    "brand": "MEDICUBE",
    "title": "Crema Hidratante Vitamin C - 55g",
    "category": "hidratantes",
    "price": 109.0,
    "oldPrice": null,
    "stock": 2,
    "discount": 0.0,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "accent",
    "img": "imagenes_productos/MKD-027.jpg",
    "desc": "Crema hidratante iluminadora formulada con alta concentración de vitamina C. Ayuda a aclarar manchas, combatir la opacidad y proteger el rostro contra los radicales libres. Para una piel visiblemente más brillante, uniforme y vital."
  },
  {
    "id": 28,
    "codigo": "MKD-028",
    "brand": "MIXSOON",
    "title": "Kit de Prueba 9-Pasos",
    "category": "kit",
    "price": 20.0,
    "oldPrice": 25.0,
    "stock": 10,
    "discount": 0.19999999999999996,
    "rating": 5.0,
    "reviews": 5.0,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-028.jpg",
    "desc": "Descubre la rutina coreana minimalista en su máxima expresión. Este kit contiene 9 muestras esenciales para limpiar, tonificar e hidratar la piel según sus necesidades. Perfecto para viajes o para probar los favoritos de la marca Mixsoon."
  },
  {
    "id": 29,
    "codigo": "MKD-029",
    "brand": "MIXSOON",
    "title": "Aceite Limpiador - 195ml",
    "category": "limpiadores",
    "price": 102.0,
    "oldPrice": null,
    "stock": 1,
    "discount": 0.0,
    "rating": 4.7,
    "reviews": 4.7,
    "badge": "En Stock",
    "badgeClass": "accent",
    "img": "imagenes_productos/MKD-029.webp",
    "desc": "Aceite limpiador formulado con ingredientes naturales que retira eficazmente el maquillaje de larga duración, protector solar e impurezas de los poros. Mantiene la piel suave e hidratada tras el lavado sin romper la barrera cutánea."
  },
  {
    "id": 30,
    "codigo": "MKD-030",
    "brand": "MIXSOON",
    "title": "Crema Hidratante - 50ml",
    "category": "hidratantes",
    "price": 109.0,
    "oldPrice": 120.0,
    "stock": 2,
    "discount": 0.09166666666666667,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-030.webp",
    "desc": "Crema facial de fórmula limpia e ingredientes esenciales que proporciona hidratación profunda y duradera. Restaura la flexibilidad cutánea y calma la irritación sin obstruir poros. Ideal para todo tipo de pieles, incluso las más sensibles."
  },
  {
    "id": 31,
    "codigo": "MKD-031",
    "brand": "MIXSOON",
    "title": "Esencia Centella Asiática - 100ml",
    "category": "serums",
    "price": 100.0,
    "oldPrice": 125.0,
    "stock": 4,
    "discount": 0.19999999999999996,
    "rating": 4.6,
    "reviews": 4.6,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-031.jpg",
    "desc": "Esencia pura concentrada al 100% en extracto de Centella Asiática. Alivia de inmediato el enrojecimiento, disminuye inflamaciones y refuerza la barrera protectora de la piel. Indispensable para pieles sensibles, reactivas o con tendencia al acné."
  },
  {
    "id": 32,
    "codigo": "MKD-032",
    "brand": "MIXSOON",
    "title": "Bean Essence - 50ml",
    "category": "hidratantes",
    "price": 110.0,
    "oldPrice": 115.0,
    "stock": 2,
    "discount": 0.04347826086956519,
    "rating": 5.0,
    "reviews": 5.0,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-032.jpg",
    "desc": "Esencia viral rica en aminoácidos procedentes de la fermentación de soja. Funciona como exfoliante suave y tratamiento ultra-hidratante: remueve células muertas, regula el sebo y deja la textura de la piel sumamente suave y reluciente."
  },
  {
    "id": 33,
    "codigo": "MKD-033",
    "brand": "NINELESS",
    "title": "Ácido Azelaico - 30ml",
    "category": "serums",
    "price": 90.0,
    "oldPrice": 110.0,
    "stock": 1,
    "discount": 0.18181818181818177,
    "rating": 5.0,
    "reviews": 5.0,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-033.webp",
    "desc": "Sérum formulado con ácido azelaico, ideal para tratar el acné, atenuar marcas post-inflamatorias y controlar las rojeces. Unifica la textura y el tono del rostro mientras limpia suavemente los poros, manteniendo la piel clara y uniforme."
  },
  {
    "id": 34,
    "codigo": "MKD-034",
    "brand": "PURITO",
    "title": "Serum Centella - 60ml",
    "category": "serums",
    "price": 96.0,
    "oldPrice": 120.0,
    "stock": 1,
    "discount": 0.19999999999999996,
    "rating": 4.7,
    "reviews": 4.7,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-034.jpg",
    "desc": "Sérum reconfortante enriquecido con extracto de Centella Asiática y niacinamida. Calma al instante la piel irritada, combate brotes y ayuda a reparar la barrera cutánea dañada. Su fórmula suave aporta hidratación equilibrada sin recargar la piel."
  },
  {
    "id": 35,
    "codigo": "MKD-035",
    "brand": "PURITO",
    "title": "Crema con Pantenol Mighty Bamboo - 100ml",
    "category": "hidratantes",
    "price": 99.0,
    "oldPrice": 110.0,
    "stock": 4,
    "discount": 0.09999999999999998,
    "rating": 5.0,
    "reviews": 5.0,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-035.jpg",
    "desc": "Crema hidratante intensiva a base de extracto de bambú y pantenol (Pro-Vitamina B5). Fortalece de inmediato la barrera cutánea, sella la humedad y protege la piel sensible del estrés ambiental. Deja el rostro reconfortado, elástico y saludable."
  },
  {
    "id": 36,
    "codigo": "MKD-036",
    "brand": "ROUND LAB",
    "title": "Bloqueador Cushion",
    "category": "solares",
    "price": 95.0,
    "oldPrice": 105.0,
    "stock": 1,
    "discount": 0.09523809523809523,
    "rating": 5.0,
    "reviews": 5.0,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-036.webp",
    "desc": "Protector solar en formato cushion práctico y portátil. Permite reaplicar la protección solar a lo largo del día sin alterar el maquillaje. Aporta un efecto refrescante, calmante e hidratante con acabado natural y sin residuo pegajoso."
  },
  {
    "id": 37,
    "codigo": "MKD-037",
    "brand": "SEOUL 1988",
    "title": "Retinal Crema Antiedad para Ojos - 30ml",
    "category": "contorno de ojos",
    "price": 99.0,
    "oldPrice": 120.0,
    "stock": 4,
    "discount": 0.17500000000000004,
    "rating": 4.7,
    "reviews": 4.7,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-037.webp",
    "desc": "Crema especializada para el contorno de ojos formulada con retinal y activos tradicionales. Ayuda a atenuar líneas de expresión, reafirmar los párpados y reducir la apariencia de cansancio. Deja la zona periocular firme, suave e hidratada."
  },
  {
    "id": 38,
    "codigo": "MKD-038",
    "brand": "SEOUL 1988",
    "title": "Retinal Serum - 30ml",
    "category": "serums",
    "price": 105.0,
    "oldPrice": 115.0,
    "stock": 1,
    "discount": 0.08695652173913049,
    "rating": 4.7,
    "reviews": 4.7,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-038.jpg",
    "desc": "Sérum antiedad potente diseñado para combatir los signos del paso del tiempo. Estimula la renovación celular, mejora la firmeza y alisa las arrugas finas, dejando el rostro visiblemente más joven, firme y uniforme."
  },
  {
    "id": 39,
    "codigo": "MKD-039",
    "brand": "SKIN 1004",
    "title": "Espuma Limpiadora Madagascar Centella - 125ml",
    "category": "limpiadores",
    "price": 74.0,
    "oldPrice": null,
    "stock": 2,
    "discount": 0.0,
    "rating": 4.6,
    "reviews": 4.6,
    "badge": "En Stock",
    "badgeClass": "accent",
    "img": "imagenes_productos/MKD-039.jpg",
    "desc": "Limpiador facial suave enriquecido con Centella Asiática de Madagascar. Elimina suciedad, restos de maquillaje y exceso de sebo de forma delicada, manteniendo el pH natural de la piel e impidiendo la tirantez o resequedad tras la limpieza."
  },
  {
    "id": 40,
    "codigo": "MKD-040",
    "brand": "SKIN 1004",
    "title": "Crema Hidratante Madagascar Centella Poremizing Light Gel Cream - 75ml",
    "category": "hidratantes",
    "price": 92.0,
    "oldPrice": 115.0,
    "stock": 1,
    "discount": 0.19999999999999996,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-040.jpg",
    "desc": "Crema en gel ultra-ligera enriquecida con sal rosada del Himalaya. Ayuda a minimizar los poros dilatados, regula el exceso de grasa y proporciona una frescura e hidratación equilibrada ideal para pieles mixtas a grasas."
  },
  {
    "id": 41,
    "codigo": "MKD-041",
    "brand": "SKIN 1004",
    "title": "Protector Solar Madagascar Centella Poremizing Velvet Finish Sunscreen - 50ml",
    "category": "solares",
    "price": 85.0,
    "oldPrice": 100.0,
    "stock": 3,
    "discount": 0.15000000000000002,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-041.webp",
    "desc": "Protección solar de amplio espectro con efecto terciopelo. Su fórmula ayuda a controlar el sebo y la visibilidad de los poros mientras protege de los rayos UV. Deja un acabado suave, mate y sedoso sin sensación pesada."
  },
  {
    "id": 42,
    "codigo": "MKD-042",
    "brand": "SKIN 1004",
    "title": "Kit de viaje Madagascar Centella - 30ml",
    "category": "kit",
    "price": 122.0,
    "oldPrice": 135.0,
    "stock": 2,
    "discount": 0.09629629629629632,
    "rating": 4.7,
    "reviews": 4.7,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-042.jpg",
    "desc": "Set imprescindible con los esenciales de la línea Madagascar Centella en tamaño miniatura. Incluye limpiador, tónico, ampolla y cremas para mantener una rutina calmante e hidratante vayas a donde vayas."
  },
  {
    "id": 43,
    "codigo": "MKD-043",
    "brand": "SKIN 1004",
    "title": "Crema Calmante Madagascar Centella Soothing Cream - 75ml",
    "category": "hidratantes",
    "price": 92.0,
    "oldPrice": 110.0,
    "stock": 2,
    "discount": 0.1636363636363637,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-043.jpg",
    "desc": "Crema hidratante diseñada para reparar y calmar pieles sensibilizadas o irritadas. Enriquecida con ceramidas y centella asiática, restaura la barrera cutánea manteniendo el rostro hidratado, suave y libre de rojeces."
  },
  {
    "id": 44,
    "codigo": "MKD-044",
    "brand": "SKIN 1004",
    "title": "Mini Ampolla Facial - 30ml",
    "category": "serums",
    "price": 50.0,
    "oldPrice": 62.5,
    "stock": 5,
    "discount": 0.19999999999999996,
    "rating": 4.8,
    "reviews": 4.8,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-044.jpg",
    "desc": "Set de mini ampollas altamente concentradas. Ideales para probar diferentes tratamientos según las necesidades diarias de tu piel: hidratación, calma, luminosidad o cuidado de poros en un formato práctico y portable."
  },
  {
    "id": 45,
    "codigo": "MKD-045",
    "brand": "SKIN 1004",
    "title": "Tónico Facial Madagascar Centella Poremizing Clear Toner - 210ml",
    "category": "tonicos",
    "price": 105.0,
    "oldPrice": null,
    "stock": 2,
    "discount": 0.0,
    "rating": 4.8,
    "reviews": 4.8,
    "badge": "En Stock",
    "badgeClass": "accent",
    "img": "imagenes_productos/MKD-045.jpg",
    "desc": "Tónico exfoliante suave con AHA y sal rosada del Himalaya. Limpia a fondo los poros, elimina células muertas y prepara la piel para los siguientes pasos de la rutina, dejándola lisa, uniforme y libre de exceso de sebo."
  },
  {
    "id": 46,
    "codigo": "MKD-046",
    "brand": "SKIN 1004",
    "title": "Espuma Limpiadora Madagascar Centella Poremizing Deep Cleansing Foam - 125ml",
    "category": "limpiadores",
    "price": 74.0,
    "oldPrice": 82.0,
    "stock": 3,
    "discount": 0.09756097560975607,
    "rating": 4.7,
    "reviews": 4.7,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-046.webp",
    "desc": "Espuma de limpieza profunda enriquecida con extracto de sal rosada. Elimina eficazmente las impurezas acumuladas en los poros y limpia el exceso de grasa, manteniendo la piel fresca, clara y equilibrada."
  },
  {
    "id": 47,
    "codigo": "MKD-047",
    "brand": "SKIN 1004",
    "title": "Crema de Ojos Madagascar Centella Probio-Cica Bakuchiol - 20ml",
    "category": "contorno de ojos",
    "price": 84.0,
    "oldPrice": 99.0,
    "stock": 1,
    "discount": 0.1515151515151515,
    "rating": 4.7,
    "reviews": 4.7,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-047.webp",
    "desc": "Contorno de ojos formulado con Probio-Cica fermentada y Bakuchiol (la alternativa natural al retinol). Suaviza las líneas de expresión, fortalece la barrera de la piel delicada y combate la hinchazón y las ojeras sin irritar."
  },
  {
    "id": 48,
    "codigo": "MKD-048",
    "brand": "SKIN 1004",
    "title": "Tónico Madagascar Centella Toning Toner - 210ml",
    "category": "tonicos",
    "price": 100.0,
    "oldPrice": 115.0,
    "stock": 2,
    "discount": 0.13043478260869568,
    "rating": 4.6,
    "reviews": 4.6,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-048.jpg",
    "desc": "Tónico diario exfoliante e hidratante enriquecido con PHA. Remueve suavemente las células muertas sin irritar la piel, calma las rojeces y equilibra el rostro, dejándolo preparado para una absorción óptima de tus sérums."
  },
  {
    "id": 49,
    "codigo": "MKD-049",
    "brand": "SKIN 1004",
    "title": "Mini Ampolla Facial Iluminadora Madagascar Centella Tone Brightening Capsule Ampoule Mini - 30ml",
    "category": "serums",
    "price": 50.0,
    "oldPrice": 62.5,
    "stock": 1,
    "discount": 0.19999999999999996,
    "rating": 4.5,
    "reviews": 4.5,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-049.jpg",
    "desc": "Ampolla concentrada en formato mini con microcápsulas iluminadoras. Ayuda a unificar el tono de la piel, atenúa manchas e hiperpigmentación y devuelve la luminosidad natural a los rostros fatigados."
  },
  {
    "id": 50,
    "codigo": "MKD-050",
    "brand": "SKIN 1004",
    "title": "Protector Solar Ligero Madagascar Centella Air Fit - 50ml",
    "category": "solares",
    "price": 89.0,
    "oldPrice": 99.0,
    "stock": 2,
    "discount": 0.101010101010101,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-050.webp",
    "desc": "Bloqueador solar físico de textura ultraligera que se absorbe sin dejar capa blanca ni sensación grasa. Ofrece alta protección UV mientras calma la piel sensible gracias a su contenido de Centella Asiática."
  },
  {
    "id": 51,
    "codigo": "MKD-051",
    "brand": "TOCOBO",
    "title": "Protector Solar Bio Watery Sun Cream - 50ml",
    "category": "solares",
    "price": 89.0,
    "oldPrice": 99.0,
    "stock": 2,
    "discount": 0.101010101010101,
    "rating": 4.5,
    "reviews": 4.5,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-051.webp",
    "desc": "Protector solar de base acuosa formulado con extracto de mungo y ácido hialurónico. Se absorbe al instante aportando una hidratación profunda y fresca. No deja sensación grasosa ni marcas blancas, perfecto para el uso diario."
  },
  {
    "id": 52,
    "codigo": "MKD-052",
    "brand": "TOCOBO",
    "title": "Aceite Labial Juicy Berry Plumping Lip Oil - 4g",
    "category": "make up",
    "price": 58.0,
    "oldPrice": 65.0,
    "stock": 3,
    "discount": 0.10769230769230764,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-052.jpg",
    "desc": "Aceite labial nutritivo que combina un toque de color jugoso con un ligero efecto plumping (volumen). Enriquecido con extractos de bayas, aporta hidratación duradera, suavidad extrema y un acabado superbrillante no pegajoso."
  },
  {
    "id": 53,
    "codigo": "MKD-053",
    "brand": "TOCOBO",
    "title": "Espuma Limpiadora Coconut Clay - 150ml",
    "category": "limpiadores",
    "price": 78.0,
    "oldPrice": 85.0,
    "stock": 2,
    "discount": 0.08235294117647063,
    "rating": 4.8,
    "reviews": 4.8,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-053.jpg",
    "desc": "Limpiador facial en espuma enriquecido con arcilla rosa y extracto de coco. Absorbe las impurezas y el exceso de grasa atrapados en los poros mientras mantiene la hidratación natural de la piel sin sensación de tirantez."
  },
  {
    "id": 54,
    "codigo": "MKD-054",
    "brand": "UNLEASHIA",
    "title": "Paleta de Sombras N°3",
    "category": "make up",
    "price": 89.0,
    "oldPrice": null,
    "stock": 3,
    "discount": 0.0,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "accent",
    "img": "imagenes_productos/MKD-054.jpg",
    "desc": "Paleta de sombras con una combinación perfecta de tonos mate sedosos y destellos deslumbrantes. Altamente pigmentadas y fáciles de difuminar, ideales para crear looks diarios sutiles o maquillajes de noche impactantes."
  },
  {
    "id": 55,
    "codigo": "MKD-055",
    "brand": "UNLEASHIA",
    "title": "Gel de Cejas N°1",
    "category": "make up",
    "price": 52.0,
    "oldPrice": 58.0,
    "stock": 3,
    "discount": 0.10344827586206895,
    "rating": 4.7,
    "reviews": 4.7,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-055.jpg",
    "desc": "Gel fijador de cejas de larga duración que peina, define y mantiene cada pelo en su lugar durante todo el día. No deja residuos blancos ni sensación rígida, logrando un acabado natural y pulido."
  },
  {
    "id": 56,
    "codigo": "MKD-056",
    "brand": "TOCOBO",
    "title": "Set de 3 Bloqueadores - 11g",
    "category": "solares",
    "price": 139.0,
    "oldPrice": 169.0,
    "stock": 1,
    "discount": 0.1775147928994083,
    "rating": 4.9,
    "reviews": 4.9,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-056.webp",
    "desc": "Tratamiento fotoprotector completo con 3 versiones de bloqueadores solares de la marca. La opción perfecta para probar o adaptar el tipo de protección solar a las necesidades diarias de tu piel (en barra, crema o textura acuosa)."
  }
];
