// Auto-generated catalog from catalogo_mikado.xlsx
const CATALOG_TIMESTAMP = 1784852422;
const PRODUCTS_DATA = [
  {
    "id": 1,
    "codigo": "MKD-001",
    "brand": "Beauty of Joseon",
    "title": "Relief Sun: Rice + Probiotics SPF50+ PA++++",
    "category": "solares",
    "price": 67.15,
    "oldPrice": 79.0,
    "stock": 25,
    "discount": 0.15,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-001.jpg",
    "desc": "Protector solar orgánico ligero con 30% extracto de arroz. No deja capa blanca."
  },
  {
    "id": 2,
    "codigo": "MKD-002",
    "brand": "COSRX",
    "title": "Advanced Snail 96 Mucin Power Essence 100ml",
    "category": "serums",
    "price": 76.5,
    "oldPrice": 85.0,
    "stock": 18,
    "discount": 0.1,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-002.jpg",
    "desc": "Esencia con 96% mucina de caracol. Repara la barrera cutánea y aporta brillo Glass Skin."
  },
  {
    "id": 3,
    "codigo": "MKD-003",
    "brand": "Anua",
    "title": "Heartleaf 77% Soothing Toner 250ml",
    "category": "tonicos",
    "price": 89.0,
    "oldPrice": null,
    "stock": 30,
    "discount": 0.0,
    "badge": "En Stock",
    "badgeClass": "accent",
    "img": "imagenes_productos/MKD-003.webp",
    "desc": "Tónico calmante para pieles sensibles y propensas a rojeces o acné."
  },
  {
    "id": 4,
    "codigo": "MKD-004",
    "brand": "Skin1004",
    "title": "Madagascar Centella Ampoule 100ml",
    "category": "serums",
    "price": 87.4,
    "oldPrice": 92.0,
    "stock": 12,
    "discount": 0.05,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-004.webp",
    "desc": "Serum concentrado 100% Centella Asiática. Calma e hidrata intensamente."
  },
  {
    "id": 5,
    "codigo": "MKD-005",
    "brand": "Laneige",
    "title": "Lip Sleeping Mask EX [Berry] 20g",
    "category": "mascarillas",
    "price": 67.5,
    "oldPrice": 75.0,
    "stock": 40,
    "discount": 0.1,
    "badge": "En Stock",
    "badgeClass": "sale",
    "img": "imagenes_productos/MKD-005.webp",
    "desc": "Mascarilla nocturna de labios de frutos rojos. Hidratación profunda 24h."
  },
  {
    "id": 6,
    "codigo": "MKD-006",
    "brand": "Skin",
    "title": "Pure Cleansing Oil 200ml",
    "category": "limpiadores",
    "price": 98.0,
    "oldPrice": null,
    "stock": 15,
    "discount": 0.0,
    "badge": "En Stock",
    "badgeClass": "accent",
    "img": "imagenes_productos/MKD-006.webp",
    "desc": "Aceite limpiador hidrofílico con 14 aceites vegetales. Remueve todo el maquillaje."
  }
];
